### ISSUE TITLE
Trouble getting it running on mac – proposed change from volume bind to docker volumes

### ISSUE THREAD

**Issue by LogFlames** [Fysiksektionen/bittan#29]
Due to an issue of ownership of the postgres_data directory (the postgres image didn't have permission to `chown` it and setting ownership to 999:999 didn't work) I wasn't able to get it running on my mac using the volume bind and had to use docker volumes instead. I think these are preferable as well as per the docker documentation: https://docs.docker.com/engine/storage/volumes/.

Creating a docker volume did get it working, and will work the same for both linux and mac.

When defining volumes in the `compose.yml` it will automatically create the volume the first time the compose is setup, and then reuse the volume.

The documentation for solving the [migration issue](https://github.com/Fysiksektionen/bittan/wiki/Backend:-Quick-Start#migration-issue) would be required to be updated.mainly that instead of deleting the `postgres_data` folder, the docker volume should be removed with `docker compose down --volumes` or by finding and removing the postgres container using `docker ps -a` and `docker rm [id]`, after which `docker volume rm backend_postgres_data` can be run. This might be preferable as `docker compose down --volumes` also will remove the `backend-server` container which might contain changed files depending on how development is performed.

```
backend/compose.yml

@@ -15,7 +15,7 @@ services:
   postgres:
     image: postgres
     volumes:
-      - ./postgres-data:/var/lib/postgresql/data
+      - postgres_data:/var/lib/postgresql/data
     environment:
       POSTGRES_DB: bittan_db
       POSTGRES_USER: postgres
@@ -28,3 +28,6 @@ services:
       interval: 1s
       timeout: 5s
       retries: 10
+
+volumes:
+  postgres_data:
```

**Comment by LogFlames** [comment]
Can create a PR if you think it is a preferable option. It's such as small diff that I felt it was easier to add it in the description.

**Comment by Gabrimari** [comment]
This looks good. 

Just to be clear, this would change the process of removing the `postgres_data` directory from:
&emsp;Shutting down the container $\to$ removing the `postgres-data` directory $\to$ starting the container.
to:
&emsp;Shutting down and removing the container $\to$ removing the `postgres_data` volume $\to$ restarting the container.

If I understood correctly this should be one method of achieving this without the need to access the container id. This should also not interfere with the `backend-server`.
```bash
docker compose stop postgres
docker compose rm postgres
docker volume rm backend_postgres_data
docker compose up -d postgres
```
Is this equivalent to your method or am I missing something?

**Comment by LogFlames** [comment]
Yes, you are complete right, that workflow is much nicer for replacing only the postgres container. Since django depends on postgres I thought it would block the removal of if, but I made that rule up 😁

**Comment by LogFlames** [comment]
I thought the wiki was part of the github project, but it seems it must be edited separately or in a local git repository. Weird decision on GH part 🤔
